fix: Render projects to only active users
envless/envless pull request #408
Opened 2023-04-22 06:28 UTC by ttebify

# Description

> Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #395

## Type of change

> Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I documented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-04-22 06:43 UTC, dahal requested changes
@ttebify#9024 thanks for submitting the PR, `withAccessControl` is amazing like we discussed.

There is one additional thing we need to fix, `/projects` page currently is rendering all the projects user has access, regardless of their status, let's restrict it to only render projects users have access to with status `active`.

2023-04-22 07:10 UTC, chetannn submitted a review, later dismissed

2023-04-23 03:46 UTC, dahal requested changes
Looks like this dropdown needs fixing. `/projects` page is not rendering project without `access.active` status but this dropdown is.

![image](https://user-images.githubusercontent.com/3684236/233818732-fbf55f54-c4cf-42c8-b7ce-f620597fb455.png)

2023-04-23 03:47 UTC, dahal commented on apps/platform/pages/projects/index.tsx
> +            status: MembershipStatus.active,
👍🏼

2023-04-23 06:42 UTC, ttebify commented
> Looks like this dropdown needs fixing. `/projects` page is not rendering project without `access.active` status but this dropdown is.
> 
> ![image](https://user-images.githubusercontent.com/3684236/233818732-fbf55f54-c4cf-42c8-b7ce-f620597fb455.png)

That was a good catch. I have resolved it now.

2023-04-23 07:14 UTC, dahal commented on apps/platform/prisma/seeds/access.ts
> +        projectOwner[project.id] === user.id
👍🏼

2023-04-23 07:20 UTC, merged