feat: update project via cli command
envless/envless pull request #472
Opened 2023-05-15 06:19 UTC by Chinedu19

# Description

> Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

> Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:

- OS with version:
- Browser with version:
- SDK / CLI with version:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I documented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-05-15 08:57 UTC, chetannn commented on apps/platform/pages/api/cli/v0/projects/index.ts
> +const projects = async (req: NextCliApiRequest, res: NextApiResponse) => {
We replaced the `v0` to `v1` so we don't need any files from `v0`.

2023-05-15 17:02 UTC, Chinedu19 commented on apps/cli/src/commands/project/create.ts
> +        await loader.stop(
Fixed, I just discovered I missed this comment

2023-05-16 04:14 UTC, dahal commented on apps/cli/src/commands/project/update.ts
> +    // These are the
Please remove these comments

2023-05-16 04:21 UTC, dahal requested changes
Overall looks good to me. Please add [Project update](https://envless.dev/docs/cli/project#update) documentation as well

https://github.com/envless/envless/blob/main/apps/docs/src/pages/cli/project.mdx#update

2023-05-16 13:58 UTC, Chinedu19 commented
just did so.

thanks for the review @dahal  and @chetannn

2023-05-18 02:09 UTC, dahal commented on apps/platform/env/index.mjs
> +    console.log(parsed, "--parsed");
Please remove this comment

2023-05-18 02:11 UTC, dahal commented on apps/platform/env/index.mjs
> +    console.log(parsed, "--parsed");
```suggestion
```

2023-05-18 02:12 UTC, dahal commented on apps/platform/pages/api/cli/v1/projects/update.ts
> +    // Any order request aside the POST request
```suggestion
```

2023-05-18 02:13 UTC, merged